### ISSUE TITLE
Offset by 50% of child width, when parent widget has no fixed size, and child size is unknown

### ISSUE THREAD

**Issue by ROTGP** [marcglasberg/align_positioned#5]
Assume we have a parent widget (a Container), with no fixed size, and positioned absolutely (within it's own parent) at a top/left (x/y) coordinate. Then we place a child widget (with no fixed or known size) within the parent. Using your library, is there a way to position the child at -0.5 of its own width and height, such that the child's center appears at the x/y coordinate of its parent? I'm trying to achieve this using your (fantastic) library but when I don't specify the width/height of the parent, I get the following error. 

```
RenderBox was not laid out: _RenderAlignPositionedBox#7e614 relayoutBoundary=up10
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1694 pos 12: 'hasSize'
```

**Comment by marcglasberg** [comment]
Hi ROTGP, I'm glad you like the package.

The `AlignPositioned`'s main goal is to position its child in relation to the `AlignPositioned` itself. This means it's best that you give the `AlignPositioned` some specific *tight constraints*.

You don't know what I mean, please read this article: https://medium.com/flutter-community/flutter-the-advanced-layout-rule-even-beginners-must-know-edc9516d1a2

Problem is, you want to position the child in relation to the `AlignPositioned`'s size, but you don't want to specify the width/height of the `AlignPositioned`, then what size do you want it to assume? It seems you want the `AlignPositioned` to size itself in relation to its child, and the child in relation to the `AlignPositioned`? It gets circular.

Or that's not what you want and you are not actually giving me enough information. 

Why don't you help me by creating a short, minimal, runnable example, that demonstrate the problem (some code that throws that error), and then telling me exactly what size you think the `AlignPositioned` widget should assume in this situation? If we can come up with a precise specification, then I can make changes to the `AlignPositioned`'s code so that it deals with your requirements.

**Comment by ROTGP** [comment]
Hi @marcglasberg , thanks for your reply. I actually solved the problem by removing the parent container entirely (which was positioned absolutely) and specified the `dx` and `dy` properties of the `AlignPositioned` object directly (combined with `moveByChildWidth: -0.5` and `moveByChildHeight: -0.5`. Once again - great work. This problem was a nightmare before I found your package.
