### ISSUE TITLE
Is it possible to make secondary widget bigger than main one in .relative

### ISSUE THREAD

**Issue by bambuh** [marcglasberg/align_positioned#8]
```
AlignPositioned.relative(
  widgetA(),
  widgetB(),
  moveByContainerHeight: 0.5,
  moveByChildHeight: 0.5,
),
```
Seems like widgetB can't be bigger than widgetA. Is it possible to do?
What I want to achieve is to make widgetA an icon and widgetB a GestureDetector of a bigger size. So that button icon perfectly fits into the design but with a bigger touch area.

**Comment by marcglasberg** [comment]
@bambuh Very sorry for the delayed response. I somehow missed this issue.

Well, in fact there are no size restrictions, and widgetB can be made larger or smaller than widgetA.

If you use `moveByContainerHeight` this is to move widgetB, not to change its size. So you must use the appropriate parameters.

I'm going to close this, but if you are still interested you can provide me with some code so that I can have a lot at it? Thank you!
